import json
from pathlib import Path
from typing import Literal
import ollama
from pydantic import BaseModel, Field


# --- Literal Types localized to Bangla ---
QuestionType = Literal[
    "তাত্ত্বিক ধারণা (Theoretical Understanding)",
    "প্রয়োগভিত্তিক (Application Based)",
    "বিশ্লেষণধর্মী (Analysis Based)"
]

DifficultyLevel = Literal[
    "১. খুব সহজ (মৌলিক জ্ঞান/স্মরণ)",
    "২. সহজ (সাধারণ অনুধাবন)",
    "৩. মাঝারি (প্রত্যক্ষ প্রয়োগ)",
    "৪. কঠিন (বিশ্লেষণ ও সংশ্লেষণ)",
    "৫. অত্যন্ত কঠিন (সমালোচনামূলক মূল্যায়ন ও উদ্ভাবন)"
]


# --- Pydantic Schema for Bangla Questions ---
class QuestionSchema(BaseModel):
    question_text: str = Field(description="সম্পূর্ণ প্রশ্ন (বাংলায়)")
    options: list[str] = Field(description="এমসিকিউ বিকল্পগুলোর তালিকা (বাংলায়), না থাকলে ফাঁকা")
    correct_answer: str = Field(description="সঠিক উত্তর বা সমাধান (বাংলায়)")
    matched_topic: str = Field(description="প্রদত্ত মূল টপিক তালিকার সাথে হুবহু মিল থাকতে হবে")
    matched_subtopic: str = Field(description="প্রদত্ত মূল সাব-টপিক তালিকার সাথে হুবহু মিল থাকতে হবে")
    question_type: QuestionType = Field(description="প্রশ্নের ধরন")
    difficulty_level: DifficultyLevel = Field(description="প্রশ্নের কাঠিন্য মাত্রা")
    logic_pattern: str = Field(
        description="প্রশ্নটির সমাধানের মূল সূত্র, যুক্তি বা কনসেপ্ট (বাংলায়) (যেমন: 'F = m * a যেখানে ভর ধ্রুবক')"
    )


class QuestionListSchema(BaseModel):
    questions: list[QuestionSchema] = Field(description="নিষ্কাশিত প্রশ্নের তালিকা")


def load_master_taxonomy(topics_file: Path) -> tuple[list[str], list[str]]:
    """Loads taxonomy lists generated by topic_mapper.py."""
    if not topics_file.exists():
        raise FileNotFoundError(f"Missing master taxonomy at {topics_file}. Run topic_mapper.py first!")

    with open(topics_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    topics = set()
    subtopics = set()

    for chap in data.get("topics_data", []):
        for top in chap.get("topics", []):
            topics.add(top["topic_name"])
            for sub in top.get("subtopics", []):
                subtopics.add(sub)

    return list(topics), list(subtopics)


def map_questions(model_name: str = "qwen2.5:7b"):
    root_dir = Path(__file__).resolve().parent.parent.parent
    q_md_folder = root_dir / "content" / "questions" / "markdown"
    topics_file = root_dir / "data" / "topics.json"
    unified_output = root_dir / "data" / "unified_dataset.json"

    # Step 1: Load Bangla master taxonomy
    valid_topics, valid_subtopics = load_master_taxonomy(topics_file)

    q_files = list(q_md_folder.glob("*.md"))
    if not q_files:
        print("⚠️ No question Markdown files found in content/questions/markdown/")
        return

    all_questions = []

    for q_file in q_files:
        print(f"🗺️ Parsing Bangla questions from: {q_file.name} using {model_name}...")
        
        with open(q_file, "r", encoding="utf-8") as f:
            q_text = f.read()

        prompt = f"""
        নিচের ফাইল থেকে প্রশ্নগুলো বিশ্লেষণ করে JSON কাঠামোতে রূপান্তর করুন।
        
        গুরুত্বপূর্ণ শর্তাবলী:
        ১. প্রশ্নের বিবরণ (question_text), বিকল্প (options), সঠিক উত্তর (correct_answer) এবং যুক্তির প্যাটার্ন (logic_pattern) সম্পূর্ণ বাংলা ভাষায় রাখুন।
        ২. 'matched_topic' অবশ্যই এই মূল তালিকার একটির সাথে হুবহু মিলতে হবে: {valid_topics}
        ৩. 'matched_subtopic' অবশ্যই এই মূল তালিকার একটির সাথে হুবহু মিলতে হবে: {valid_subtopics}

        শ্রেণিবিভাগের নিয়মাবলী:
        - Question Types:
          * 'তাত্ত্বিক ধারণা (Theoretical Understanding)'
          * 'প্রয়োগভিত্তিক (Application Based)'
          * 'বিশ্লেষণধর্মী (Analysis Based)'

        - Difficulty Levels:
          * '১. খুব সহজ (মৌলিক জ্ঞান/স্মরণ)' (~৯৫% শিক্ষার্থী উত্তর পারে)
          * '২. সহজ (সাধারণ অনুধাবন)' (~৮০% শিক্ষার্থী উত্তর পারে)
          * '৩. মাঝারি (প্রত্যক্ষ প্রয়োগ)' (~৬০% শিক্ষার্থী উত্তর পারে)
          * '৪. কঠিন (বিশ্লেষণ ও সংশ্লেষণ)' (~৩০% শিক্ষার্থী উত্তর পারে)
          * '৫. অত্যন্ত কঠিন (সমালোচনামূলক মূল্যায়ন ও উদ্ভাবন)' (~৫-১০% শীর্ষ শিক্ষার্থী পারে)

        প্রশ্নের ফাইল (Text):
        {q_text}
        """

        try:
            response = ollama.chat(
                model=model_name,
                messages=[{"role": "user", "content": prompt}],
                format=QuestionListSchema.model_json_schema()
            )

            res_data = json.loads(response["message"]["content"])
            questions_list = res_data.get("questions", [])

            for idx, q in enumerate(questions_list, start=1):
                q["question_id"] = f"{q_file.stem}_q{idx}"
                q["source_file"] = q_file.name
                all_questions.append(q)

        except Exception as e:
            print(f"❌ Error parsing questions from {q_file.name}: {e}")

    # Step 2: Write parsed output to unified JSON file with Bangla encoding
    unified_output.parent.mkdir(parents=True, exist_ok=True)
    with open(unified_output, "w", encoding="utf-8") as f:
        json.dump(
            {
                "total_questions": len(all_questions),
                "questions": all_questions
            },
            f,
            indent=2,
            ensure_ascii=False  # Key setting: prevents encoding Bangla characters as escape sequences (\u0985)
        )

    print(f"✅ Published Bangla unified dataset to: {unified_output}")


if __name__ == "__main__":
    map_questions()