"""
content/converters/pdf_to_md.py
Converts document PDFs into Markdown using Hugging Face Nougat models directly.
"""

import sys
from pathlib import Path
import torch
import pymupdf
from PIL import Image
from transformers import NougatProcessor, VisionEncoderDecoderModel

_PROCESSOR = None
_MODEL = None


def get_hf_nougat():
    global _PROCESSOR, _MODEL
    if _MODEL is None:
        print("⏳ Loading Hugging Face Nougat Model (facebook/nougat-small)...")
        _PROCESSOR = NougatProcessor.from_pretrained("facebook/nougat-small")
        _MODEL = VisionEncoderDecoderModel.from_pretrained("facebook/nougat-small")
        
        device = "cuda" if torch.cuda.is_available() else "cpu"
        _MODEL.to(device)
        _MODEL.eval()
    return _PROCESSOR, _MODEL


def clean_markdown_output(text: str) -> str:
    """Safely cleans output generated by Nougat."""
    # Convert escaped newlines if present and trim whitespace
    cleaned = text.replace(r"\n", "\n").strip()
    return cleaned


def convert_pdf_to_md(pdf_filename: str) -> Path:
    base_dir = Path(__file__).resolve().parent.parent.parent

    raw_path = base_dir / "content" / "documents" / "raw_pdf" / pdf_filename
    scanned_path = base_dir / "content" / "documents" / "image_pdf" / pdf_filename

    if raw_path.exists():
        input_pdf = raw_path
    elif scanned_path.exists():
        input_pdf = scanned_path
    else:
        raise FileNotFoundError(
            f"PDF file '{pdf_filename}' not found in raw_pdf/ or image_pdf/."
        )

    output_md = base_dir / "content" / "documents" / "markdown" / f"{input_pdf.stem}.md"
    output_md.parent.mkdir(parents=True, exist_ok=True)

    print(f"🔄 Converting PDF with Hugging Face Nougat: {pdf_filename}...")

    processor, model = get_hf_nougat()
    device = next(model.parameters()).device

    doc = pymupdf.open(input_pdf)
    extracted_pages = []

    for page_num in range(len(doc)):
        page = doc[page_num]
        pix = page.get_pixmap(dpi=150)
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

        pixel_values = processor(img, return_tensors="pt").pixel_values.to(device)

        outputs = model.generate(
            pixel_values,
            min_length=1,
            max_new_tokens=3584,
            bad_words_ids=[[processor.tokenizer.unk_token_id]],
        )

        # Decode tokens safely
        sequence = processor.batch_decode(outputs, skip_special_tokens=True)[0]
        page_md = clean_markdown_output(sequence)

        extracted_pages.append(f"<!-- Page {page_num + 1} -->\n{page_md}")

    doc.close()

    full_markdown = "\n\n---\n\n".join(extracted_pages)
    with open(output_md, "w", encoding="utf-8") as f:
        f.write(full_markdown)

    print(f"✅ Conversion complete: {output_md.name}")
    return output_md


if __name__ == "__main__":
    if len(sys.argv) > 1:
        target_file = sys.argv[1]
    else:
        target_file = input("Enter PDF filename: ").strip()

    if target_file:
        convert_pdf_to_md(target_file)